### ISSUE TITLE
-3009 (DNS Failed), any idea how to debug?

### ISSUE THREAD

**Issue by janjongboom** [ARMmbed/wifi-ism43362#74]
Hi @jeromecoutant, one of our users is using this WiFi radio on the ST B-L475E-IOT01A but sees all requests fail with a `-3009` error. Looking at the NSAPI error table in Mbed OS that seems like a DNS error, so I'm suspecting a firewall issue somewhere. Do we have any good idea on how we could debug this properly for this chip?

Some info:

https://forum.edgeimpulse.com/t/uploading-finishes-but-no-data-collected/303/7

**Comment by jeromecoutant** [comment]
@JeanMarcR Could you have a look ?
Thx

**Comment by JeanMarcR** [comment]
Yes, I am looking at.

**Comment by JeanMarcR** [comment]
Hi all,

You could try the following steps :
- Removing the gethostbyname() or getb hostbyname_async() from your code,
- Using the IP address of the server (you would like to connect),
- Checking your application. 
If the problem is due to DNS server, your application must run correctly.
Maybe there is a firewall issue.
So, to enable communication with the DNS server, firewall must authorize  UDP and TCP connections on port 53.

Best regards

**Comment by jeromecoutant** [comment]
Hi @janjongboom 
Could you try #78 ?
Thx

**Comment by jeromecoutant** [comment]
Any update ?
Thx

**Comment by janjongboom** [comment]
@jeromecoutant Sorry, GH notifications overload. I can't test this for the user on an unlanded PR. I'll update the WiFi driver for the firmware once it lands (hard to test I know!).
